# Generated by Django 4.2.7 on 2023-12-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedgehog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Mail', models.EmailField(blank=True, max_length=100, null=True)),
                ('level', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
    ]
