# Generated by Django 4.2.7 on 2023-12-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedgehog', '0002_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ivent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('DateTime', models.DateTimeField()),
                ('Fee', models.IntegerField()),
                ('Capacity', models.IntegerField()),
                ('Comment', models.TextField()),
            ],
        ),
    ]
