# Generated by Django 4.2.7 on 2023-12-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedgehog', '0003_ivent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ivent',
            new_name='Event',
        ),
    ]
