# Generated by Django 4.2.7 on 2023-12-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedgehog', '0004_rename_ivent_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Name',
            new_name='EventName',
        ),
        migrations.AddField(
            model_name='event',
            name='EventType',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='Time',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
